#!/usr/bin/env python3
"""Programmatic Tool Calling (PTC) Server for bash execution.

Bash equivalent of `ptc_server.py`. Speaks the same outer JSON protocol
on stdin/stdout, but runs user **bash** code instead of Python. Tool calls
from bash are routed through two named pipes (FIFOs) so user code can
treat each tool as a regular bash function:

    weather_lookup '{"city":"NYC"}'

The wrapper reads the result on stdout — caller pipes through `jq` to
extract fields.

Outer protocol (identical to ptc_server.py):
1. Host writes  {"code": "...", "tools": [{"name": ..., ...}]} + delimiter on stdin.
2. On each tool call, server writes
   {"type": "tool_calls", "calls": [{"id": ..., "name": ..., "input": ...}]}
   to stdout.
3. Host writes back
   {"type": "tool_results", "results": [{"call_id": ..., "result": ..., "is_error": ...}]}
   on stdin.
4. On bash exit, server writes
   {"type": "completed", "stdout": ..., "stderr": ...}.
5. On any error, server writes {"type": "error", ...}.

Inner protocol (bash <-> this script via FIFOs):
- bash writes one JSON line `{"name":"...","input":{...}}` to call.fifo, then
  reads one line from result.fifo. The line on result.fifo is the JSON-encoded
  `result` value (or `{"error": "..."}` if the host reported is_error).
- One tool call at a time; bash blocks on `read` until result arrives.

Compromises (vs the Python PTC server):
- Sequential tool calls only — bash has no native asyncio. Acceptable because
  shell scripts are inherently sequential.
- Tool inputs are JSON strings; user bash code uses `jq` to extract fields.
- `jq` is required in the sandbox image (entrypoint.sh fails fast if missing).
"""

import asyncio
import json
import os
import re
import shlex
import sys
import uuid
from pathlib import Path

DELIMITER = "\n---PTC_END---\n"

# Per-sandbox FIFO directory, hidden so detect_generated_files skips it.
# Override via PTC_BASH_DIR for local testing outside the sandbox.
PTC_DIR = Path(os.environ.get("PTC_BASH_DIR", "/mnt/data/.ptc"))
CALL_FIFO = PTC_DIR / "call.fifo"
RESULT_FIFO = PTC_DIR / "result.fifo"
RC_PATH = PTC_DIR / "rc.sh"
USER_CODE_PATH = PTC_DIR / "user.sh"

_real_stdin = sys.stdin
_real_stdout = sys.stdout

# Bash identifier rules: [A-Za-z_][A-Za-z0-9_]*. We refuse to wrap any tool
# whose name doesn't match — both for shell safety and because the user
# couldn't call it from bash anyway.
_VALID_BASH_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _write_message(msg: dict) -> None:
    _real_stdout.write(json.dumps(msg) + DELIMITER)
    _real_stdout.flush()


def _read_message() -> dict:
    buf = ""
    while True:
        line = _real_stdin.readline()
        if not line:
            raise EOFError("stdin closed")
        buf += line
        if DELIMITER in buf:
            return json.loads(buf.split(DELIMITER)[0])


def _generate_rcfile(tools: list) -> str:
    """Generate one bash function per declared tool."""
    lines = [
        "# Auto-generated by ptc_bash_server.py — DO NOT edit",
        "# Each tool function takes a JSON argument and returns the JSON result on stdout.",
        f"export PTC_CALL_FIFO={shlex.quote(str(CALL_FIFO))}",
        f"export PTC_RESULT_FIFO={shlex.quote(str(RESULT_FIFO))}",
        "",
    ]
    for tool in tools:
        name = tool.get("name", "")
        if not _VALID_BASH_NAME.match(name):
            continue
        lines.append(
            f"{name}() {{\n"
            # Use an explicit conditional rather than ${1:-{}} — the brace-default
            # form parses as ${1:-{} followed by a literal }, which appends a
            # stray brace whenever $1 is set.
            f'    local input_json="$1"\n'
            f'    if [ -z "$input_json" ]; then input_json="{{}}"; fi\n'
            f"    local payload\n"
            f"    payload=$(jq -c -n --arg name {shlex.quote(name)} "
            f'--argjson input "$input_json" \'{{name:$name,input:$input}}\' 2>/dev/null) || \\\n'
            f"    payload=$(jq -c -n --arg name {shlex.quote(name)} "
            f'--arg input "$input_json" \'{{name:$name,input:$input}}\')\n'
            f'    printf \'%s\\n\' "$payload" > "$PTC_CALL_FIFO"\n'
            f"    local result\n"
            f'    IFS= read -r result < "$PTC_RESULT_FIFO"\n'
            f'    printf \'%s\\n\' "$result"\n'
            f"}}\n"
        )
    return "\n".join(lines)


async def _run(code: str, tools: list) -> dict:
    """Spawn bash with the generated rc and route tool calls between bash and the host."""
    PTC_DIR.mkdir(mode=0o755, exist_ok=True)
    for fifo in (CALL_FIFO, RESULT_FIFO):
        try:
            os.unlink(fifo)
        except FileNotFoundError:
            pass
        os.mkfifo(fifo, 0o600)

    RC_PATH.write_text(_generate_rcfile(tools))
    USER_CODE_PATH.write_text(code)

    # Spawn bash. --rcfile loads our wrappers; user code runs via -c so that
    # functions defined in rc.sh are available without an interactive shell.
    proc = await asyncio.create_subprocess_exec(
        "bash",
        "--rcfile",
        str(RC_PATH),
        "-i",
        str(USER_CODE_PATH),
        stdin=asyncio.subprocess.DEVNULL,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    # Open both FIFOs O_RDWR so we never see EOF when bash closes its end
    # between calls (bash opens/closes per call). Non-blocking so we can
    # cooperate with asyncio.add_reader for the call channel.
    call_fd = os.open(str(CALL_FIFO), os.O_RDWR | os.O_NONBLOCK)
    result_fd = os.open(str(RESULT_FIFO), os.O_RDWR | os.O_NONBLOCK)

    loop = asyncio.get_event_loop()
    call_queue: asyncio.Queue = asyncio.Queue()
    call_buf = bytearray()

    def on_call_readable() -> None:
        try:
            chunk = os.read(call_fd, 4096)
        except (BlockingIOError, OSError):
            return
        if not chunk:
            return
        call_buf.extend(chunk)
        # Drain complete lines into the queue.
        while b"\n" in call_buf:
            idx = call_buf.index(b"\n")
            line = bytes(call_buf[:idx]).decode("utf-8", errors="replace").strip()
            del call_buf[: idx + 1]
            if line:
                call_queue.put_nowait(line)

    loop.add_reader(call_fd, on_call_readable)
    bash_exit = asyncio.create_task(proc.wait())

    error_message: str | None = None

    try:
        while True:
            get_call = asyncio.create_task(call_queue.get())
            done, _ = await asyncio.wait(
                {get_call, bash_exit},
                return_when=asyncio.FIRST_COMPLETED,
            )

            if get_call in done:
                line = get_call.result()
                try:
                    call = json.loads(line)
                except json.JSONDecodeError:
                    # Malformed call from bash — return an error so bash unblocks.
                    os.write(result_fd, b'{"error":"invalid JSON from bash"}\n')
                    continue

                call_id = uuid.uuid4().hex[:12]
                _write_message(
                    {
                        "type": "tool_calls",
                        "calls": [
                            {
                                "id": call_id,
                                "name": call.get("name"),
                                "input": call.get("input", {}),
                            }
                        ],
                    }
                )

                try:
                    response = _read_message()
                except EOFError:
                    error_message = "Host stdin closed mid-execution"
                    break

                if response.get("type") != "tool_results":
                    error_message = (
                        f"Expected tool_results, got {response.get('type')!r}"
                    )
                    os.write(result_fd, b'{"error":"protocol mismatch"}\n')
                    break

                results = response.get("results", [])
                target = next(
                    (r for r in results if r.get("call_id") == call_id), None
                )
                if target is None and results:
                    target = results[0]

                if target is None:
                    os.write(result_fd, b'{"error":"no tool result returned"}\n')
                    continue

                if target.get("is_error"):
                    err = target.get("error_message", "tool error")
                    payload = json.dumps({"error": err})
                else:
                    # Round-trip the tool result as JSON. Strings, numbers,
                    # objects all serialize fine; user code parses with jq.
                    payload = json.dumps(target.get("result"))

                os.write(result_fd, (payload + "\n").encode("utf-8"))

            if bash_exit in done:
                if not get_call.done():
                    get_call.cancel()
                    try:
                        await get_call
                    except (asyncio.CancelledError, Exception):
                        pass
                break
    finally:
        try:
            loop.remove_reader(call_fd)
        except (ValueError, OSError):
            pass

    # Make sure bash has fully exited before we read its pipes.
    if not bash_exit.done():
        try:
            await asyncio.wait_for(bash_exit, timeout=5)
        except asyncio.TimeoutError:
            try:
                proc.kill()
            except ProcessLookupError:
                pass
            await proc.wait()

    stdout_bytes = b""
    stderr_bytes = b""
    if proc.stdout is not None:
        try:
            stdout_bytes = await proc.stdout.read()
        except Exception:
            pass
    if proc.stderr is not None:
        try:
            stderr_bytes = await proc.stderr.read()
        except Exception:
            pass

    os.close(call_fd)
    os.close(result_fd)
    for fifo in (CALL_FIFO, RESULT_FIFO):
        try:
            os.unlink(fifo)
        except FileNotFoundError:
            pass
    try:
        RC_PATH.unlink()
    except FileNotFoundError:
        pass
    try:
        USER_CODE_PATH.unlink()
    except FileNotFoundError:
        pass
    try:
        PTC_DIR.rmdir()
    except OSError:
        # Directory may still contain files the user wrote; leave it for
        # the orchestrator's normal sandbox teardown.
        pass

    stdout = stdout_bytes.decode("utf-8", errors="replace")
    stderr = stderr_bytes.decode("utf-8", errors="replace")

    if error_message:
        return {
            "type": "error",
            "error": error_message,
            "stdout": stdout,
            "stderr": stderr,
        }

    if proc.returncode == 0:
        return {"type": "completed", "stdout": stdout, "stderr": stderr}

    return {
        "type": "error",
        "error": f"bash exited with code {proc.returncode}",
        "stdout": stdout,
        "stderr": stderr,
    }


def main() -> None:
    # Inside the sandbox /mnt/data exists; for local testing PTC_BASH_DIR
    # points elsewhere and chdir is unnecessary.
    if "PTC_BASH_DIR" not in os.environ:
        try:
            os.chdir("/mnt/data")
        except OSError:
            pass

    try:
        request = _read_message()
    except Exception as exc:
        _write_message(
            {"type": "error", "error": f"Failed to read initial request: {exc}"}
        )
        return

    code = request.get("code", "")
    tools = request.get("tools", [])
    if not code:
        _write_message({"type": "error", "error": "No code provided"})
        return

    try:
        result = asyncio.run(_run(code, tools))
    except Exception as exc:
        result = {"type": "error", "error": f"bash PTC failed: {exc}"}

    _write_message(result)


if __name__ == "__main__":
    main()
