#!/usr/bin/env python3
"""Inject OBA cover page into a pandoc-generated DOCX.

Usage:
    python3 inject_cover.py <input.docx> <output.docx> --title "..." [--subtitle "..."] [--author "..."] [--date "..."]

This script takes a DOCX generated by pandoc (with reference-pandoc.docx) and:
1. Transplants styles, numbering, settings, theme, endnotes, footer from template-base.docx
2. Remaps pandoc style IDs (English) to OBA template style IDs (French)
3. Removes the redundant Title paragraph pandoc generates from # H1
4. Injects the OBA cover page (title table + logo + version table + page break)
5. Adds missing relationships (images, footer, endnotes) and content types
6. Packs and validates the output

The result is a fully branded OBA document combining pandoc's robust markdown
parsing with the complete OBA template branding.

Key design decisions:
- settings.xml references endnotes.xml → both must be transplanted together
- footerReference must be inserted at position 0 in sectPr (OOXML element ordering)
- Pandoc uses English style IDs (Heading1, BodyText) but OBA uses French (Titre1, Normal)
  → all pStyle/rStyle references in the body must be remapped
- Pandoc maps '# H1' with --shift-heading-level-by=-1 to 'Title' style → redundant with cover
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

from lxml import etree

# Paths
SCRIPTS_DIR = Path(__file__).parent
SKILLS_ROOT = SCRIPTS_DIR.parent
TEMPLATE_BASE = SKILLS_ROOT / "templates" / "onbehalfai" / "template-base.docx"
OFFICE_DIR = SCRIPTS_DIR / "office"

# Namespaces
W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
CT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"
REL_IMAGE_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
REL_FOOTER_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer"

# Pandoc style ID → OBA template style ID mapping
PANDOC_STYLE_MAP = {
    # Headings
    "Title": "Titre",
    "Subtitle": "Sous-titre",
    "Heading1": "Titre1",
    "Heading2": "Titre2",
    "Heading3": "Titre3",
    "Heading4": "Titre4",
    "Heading5": "Titre5",
    # Body text
    "FirstParagraph": "Normal",
    "BodyText": "Normal",
    "BlockText": "Normal",
    "Compact": "Paragraphedeliste",
    # Code (pandoc source code styles → OBA code style)
    "SourceCode": "Code",
    "VerbatimChar": "CodeCar",
    # Pandoc syntax highlighting token styles (character styles)
    # These don't have OBA equivalents — keep them as-is or map to code
    "NormalTok": "CodeCar",
    "KeywordTok": "CodeCar",
    "DataTypeTok": "CodeCar",
    "DecValTok": "CodeCar",
    "FunctionTok": "CodeCar",
    "CharTok": "CodeCar",
    "StringTok": "CodeCar",
    "CommentTok": "CodeCar",
    "OperatorTok": "CodeCar",
    "BuiltInTok": "CodeCar",
    "ExtensionTok": "CodeCar",
    "AttributeTok": "CodeCar",
    "VariableTok": "CodeCar",
}


def _w(tag):
    return f"{{{W_NS}}}{tag}"


def extract_cover_elements(template_path):
    """Extract cover page elements (2 tables + spacing) from template-base.docx.

    Returns (elements_list, media_files_dict, image_rels_list)
    """
    with zipfile.ZipFile(template_path) as z:
        doc_xml = z.read("word/document.xml")
        rels_xml = z.read("word/_rels/document.xml.rels")

        media_files = {}
        for name in z.namelist():
            if name.startswith("word/media/"):
                media_files[name] = z.read(name)

        rels_tree = etree.fromstring(rels_xml)
        image_rels = []
        for rel in rels_tree:
            if rel.get("Type", "") == REL_IMAGE_TYPE:
                image_rels.append({
                    "id": rel.get("Id"),
                    "target": rel.get("Target"),
                })

    tree = etree.fromstring(doc_xml)
    body = tree.find(_w("body"))
    children = list(body)

    # Cover = elements [0] to [7]:
    # [0] = title/logo table, [1-5] = spacing, [6] = version table, [7] = trailing para
    cover_elements = []
    for i in range(min(8, len(children))):
        child = children[i]
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag
        if tag == "p":
            pStyle = child.find(f".//{{{W_NS}}}pStyle")
            if pStyle is not None and "Titre" in pStyle.get(f"{{{W_NS}}}val", ""):
                break
        cover_elements.append(child)

    return cover_elements, media_files, image_rels


def inject_cover(input_docx, output_docx, title, subtitle="", author="", date=""):
    """Inject cover page into a pandoc-generated DOCX."""

    tmpdir = tempfile.mkdtemp()

    try:
        # === Step 1: Extract input DOCX ===
        input_dir = os.path.join(tmpdir, "input")
        with zipfile.ZipFile(input_docx, "r") as z:
            z.extractall(input_dir)

        # === Step 2: Transplant template files (styles, numbering, etc.) ===
        with zipfile.ZipFile(TEMPLATE_BASE) as zt:
            files_to_transplant = [
                "word/styles.xml",
                "word/numbering.xml",
                "word/settings.xml",
                "word/theme/theme1.xml",
                "word/endnotes.xml",
            ]
            if "word/footer1.xml" in zt.namelist():
                files_to_transplant.append("word/footer1.xml")

            for fname in files_to_transplant:
                if fname in zt.namelist():
                    dest = os.path.join(input_dir, fname)
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    with open(dest, "wb") as f:
                        f.write(zt.read(fname))
        print(f"Transplanted {len(files_to_transplant)} template files (styles, numbering, settings, theme, footer)")

        # === Step 3: Extract cover elements and media from template ===
        cover_elements, media_files, template_image_rels = extract_cover_elements(TEMPLATE_BASE)

        media_dir = os.path.join(input_dir, "word", "media")
        os.makedirs(media_dir, exist_ok=True)
        for media_path, media_data in media_files.items():
            dest = os.path.join(input_dir, media_path)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "wb") as f:
                f.write(media_data)

        # === Step 4: Update relationships (single parse) ===
        rels_path = os.path.join(input_dir, "word", "_rels", "document.xml.rels")
        rels_tree = etree.parse(rels_path)
        rels_root = rels_tree.getroot()

        existing_rids = set(rel.get("Id", "") for rel in rels_root)
        footer_rid_for_sectpr = None

        # Add image relationships
        for img_rel in template_image_rels:
            if img_rel["id"] not in existing_rids:
                new_rel = etree.SubElement(rels_root, "Relationship")
                new_rel.set("Id", img_rel["id"])
                new_rel.set("Type", REL_IMAGE_TYPE)
                new_rel.set("Target", img_rel["target"])
                existing_rids.add(img_rel["id"])

        # Add endnotes relationship if missing
        REL_ENDNOTES_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes"
        has_endnotes_rel = any(
            rel.get("Type", "") == REL_ENDNOTES_TYPE for rel in rels_root
        )
        if not has_endnotes_rel:
            max_id = max(
                (int(rid[3:]) for rid in existing_rids if rid.startswith("rId") and rid[3:].isdigit()),
                default=0,
            )
            endnotes_rid = f"rId{max_id + 1}"
            new_rel = etree.SubElement(rels_root, "Relationship")
            new_rel.set("Id", endnotes_rid)
            new_rel.set("Type", REL_ENDNOTES_TYPE)
            new_rel.set("Target", "endnotes.xml")
            existing_rids.add(endnotes_rid)

        # Add footer relationship
        has_footer_rel = any(
            rel.get("Type", "") == REL_FOOTER_TYPE for rel in rels_root
        )
        if not has_footer_rel:
            max_id = max(
                (int(rid[3:]) for rid in existing_rids if rid.startswith("rId") and rid[3:].isdigit()),
                default=0,
            )
            footer_rid = f"rId{max_id + 1}"
            new_rel = etree.SubElement(rels_root, "Relationship")
            new_rel.set("Id", footer_rid)
            new_rel.set("Type", REL_FOOTER_TYPE)
            new_rel.set("Target", "footer1.xml")
            footer_rid_for_sectpr = footer_rid

        rels_tree.write(rels_path, xml_declaration=True, encoding="UTF-8", standalone=True)

        # === Step 5: Update [Content_Types].xml (single parse) ===
        ct_path = os.path.join(input_dir, "[Content_Types].xml")
        ct_tree = etree.parse(ct_path)
        ct_root = ct_tree.getroot()

        # Add image extensions
        existing_extensions = set(
            d.get("Extension", "") for d in ct_root.findall(f"{{{CT_NS}}}Default")
        )
        image_types = {"png": "image/png", "svg": "image/svg+xml", "jpeg": "image/jpeg", "jpg": "image/jpeg"}
        for ext, ctype in image_types.items():
            if ext not in existing_extensions and any(f.endswith(f".{ext}") for f in media_files):
                default = etree.SubElement(ct_root, f"{{{CT_NS}}}Default")
                default.set("Extension", ext)
                default.set("ContentType", ctype)

        # Add endnotes + footer content types
        existing_overrides = set(
            o.get("PartName", "") for o in ct_root.findall(f"{{{CT_NS}}}Override")
        )
        if "/word/endnotes.xml" not in existing_overrides:
            override = etree.SubElement(ct_root, f"{{{CT_NS}}}Override")
            override.set("PartName", "/word/endnotes.xml")
            override.set("ContentType", "application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml")
        if "/word/footer1.xml" not in existing_overrides:
            override = etree.SubElement(ct_root, f"{{{CT_NS}}}Override")
            override.set("PartName", "/word/footer1.xml")
            override.set("ContentType", "application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml")

        ct_tree.write(ct_path, xml_declaration=True, encoding="UTF-8", standalone=True)

        # === Step 6: Modify document.xml ===
        doc_path = os.path.join(input_dir, "word", "document.xml")
        doc_tree = etree.parse(doc_path)
        doc_root = doc_tree.getroot()
        body = doc_root.find(_w("body"))

        # 6a. Remap pandoc style IDs to OBA template style IDs
        remap_count = 0
        for pStyle in body.iter(_w("pStyle")):
            val = pStyle.get(_w("val"), "")
            if val in PANDOC_STYLE_MAP:
                pStyle.set(_w("val"), PANDOC_STYLE_MAP[val])
                remap_count += 1
        for rStyle in body.iter(_w("rStyle")):
            val = rStyle.get(_w("val"), "")
            if val in PANDOC_STYLE_MAP:
                rStyle.set(_w("val"), PANDOC_STYLE_MAP[val])
                remap_count += 1
        if remap_count:
            print(f"Remapped {remap_count} style reference(s) from pandoc IDs to OBA IDs")

        # 6b. Replace placeholders in cover elements
        for elem in cover_elements:
            for t_elem in elem.iter(_w("t")):
                if t_elem.text is None:
                    continue
                t_elem.text = (
                    t_elem.text
                    .replace("[TITRE DU DOCUMENT]", title)
                    .replace("[Sous-titre du document]", subtitle)
                    .replace("[Auteur]", author)
                    .replace("[Date]", date)
                )

        # 6b. Remove redundant Title/Subtitle paragraphs from pandoc body
        # (pandoc maps # H1 with --shift-heading-level-by=-1 to Title style)
        to_remove = []
        for child in list(body):
            if child.tag != _w("p"):
                continue
            pStyle = child.find(f".//{_w('pStyle')}")
            if pStyle is None:
                continue
            style_val = pStyle.get(_w("val"), "")
            if style_val in ("Title", "Titre", "Subtitle", "Sous-titre"):
                to_remove.append(child)
            elif "eading" in style_val or style_val.startswith("Titre"):
                break  # Stop at first real heading

        for elem in to_remove:
            body.remove(elem)
        if to_remove:
            print(f"Removed {len(to_remove)} redundant Title/Subtitle paragraph(s) from body")

        # 6c. Insert cover + page break at the start
        page_break = etree.Element(_w("p"))
        r = etree.SubElement(page_break, _w("r"))
        br = etree.SubElement(r, _w("br"))
        br.set(_w("type"), "page")

        insert_idx = 0
        for elem in cover_elements:
            body.insert(insert_idx, elem)
            insert_idx += 1
        body.insert(insert_idx, page_break)

        # 6d. Add footerReference to sectPr if needed
        # OOXML requires footerReference early in sectPr (before endnotePr, pgSz, etc.)
        if footer_rid_for_sectpr:
            for sectPr in doc_root.findall(f".//{_w('sectPr')}"):
                footer_ref = etree.Element(_w("footerReference"))
                footer_ref.set(_w("type"), "default")
                footer_ref.set(f"{{{R_NS}}}id", footer_rid_for_sectpr)
                sectPr.insert(0, footer_ref)

        doc_tree.write(doc_path, xml_declaration=True, encoding="UTF-8", standalone=True)

        # === Step 7: Pack and validate ===
        pack_script = str(OFFICE_DIR / "pack.py")
        result = subprocess.run(
            ["python3", pack_script, input_dir, output_docx, "--original", input_docx],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"Pack error:\n{result.stdout}\n{result.stderr}", file=sys.stderr)
            sys.exit(1)
        print(result.stdout, end="")

        validate_script = str(OFFICE_DIR / "validate.py")
        result = subprocess.run(
            ["python3", validate_script, output_docx],
            capture_output=True, text=True,
        )
        print(result.stdout, end="")
        if result.returncode != 0:
            print(f"Validation warnings: {result.stderr}", file=sys.stderr)

        print(f"Success: {output_docx}")

    finally:
        shutil.rmtree(tmpdir)


def main():
    parser = argparse.ArgumentParser(description="Inject OBA cover page into pandoc DOCX output")
    parser.add_argument("input", help="Input DOCX (pandoc-generated)")
    parser.add_argument("output", help="Output DOCX with cover page")
    parser.add_argument("--title", required=True, help="Document title")
    parser.add_argument("--subtitle", default="", help="Document subtitle")
    parser.add_argument("--author", default="", help="Author name")
    parser.add_argument("--date", default="", help="Date (DD/MM/YYYY)")

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: {args.input} not found", file=sys.stderr)
        sys.exit(1)

    inject_cover(args.input, args.output, args.title, args.subtitle, args.author, args.date)


if __name__ == "__main__":
    main()
