#!/usr/bin/env python3
"""Inject OBA cover page into a pandoc-generated DOCX.

Usage:
    python3 inject_cover.py <input.docx> <output.docx> --title "..." [--subtitle "..."] [--author "..."] [--date "..."]

This script takes a DOCX generated by pandoc (with reference-pandoc.docx) and:
1. Transplants 6 files from template-base.docx (styles, numbering, settings, theme, endnotes, footer)
2. Remaps pandoc style IDs (English) to OBA template style IDs (French)
   - Context-aware: Compact+numPr → Paragraphedeliste; Compact without numPr → Normal
   - CodeCar token styles (NormalTok, KeywordTok, etc.) REMOVED outside Code paragraphs
3. Removes horizontal rule separators (empty paragraphs from markdown ---)
4. Adds light gray borders (#CCCCCC) to all content tables
5. Removes left indent (w:ind) from table cell paragraphs
6. Removes the redundant Title paragraph (pandoc maps # H1 to Title with --shift-heading-level-by)
7. Rebuilds version table as 4 columns (Date, Objet, Auteur, Version)
8. Injects the OBA cover page (title/logo table + spacing + version table + page break)
9. Adds missing relationships (images, footer, endnotes) and content types
10. Packs and validates the output

The result is a fully branded OBA document combining pandoc's robust markdown
parsing with the complete OBA template branding.

Key design decisions:
- settings.xml references endnotes.xml → both must be transplanted together
- footerReference must be inserted at position 0 in sectPr (OOXML element ordering)
- tblBorders must precede tblLook in tblPr (OOXML element ordering)
- Pandoc uses English style IDs (Heading1, BodyText) but OBA uses French (Titre1, Normal)
- Compact style is context-aware: with numPr=list item, without numPr=table cell
- CodeCar token styles are REMOVED (not remapped) outside code blocks to avoid
  applying code formatting to headings, tables, and normal text
- Pandoc maps '# H1' with --shift-heading-level-by=-1 to 'Title' style → redundant with cover
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

from lxml import etree

# Paths
SCRIPTS_DIR = Path(__file__).parent
SKILLS_ROOT = SCRIPTS_DIR.parent
TEMPLATE_BASE = SKILLS_ROOT / "templates" / "onbehalfai" / "template-base.docx"
OFFICE_DIR = SCRIPTS_DIR / "office"

# Namespaces
W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
CT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"
REL_IMAGE_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
REL_FOOTER_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer"

# Pandoc style ID → OBA template style ID mapping
PANDOC_STYLE_MAP = {
    # Headings
    "Title": "Titre",
    "Subtitle": "Sous-titre",
    "Heading1": "Titre1",
    "Heading2": "Titre2",
    "Heading3": "Titre3",
    "Heading4": "Titre4",
    "Heading5": "Titre5",
    # Body text
    "FirstParagraph": "Normal",
    "BodyText": "Normal",
    "BlockText": "Normal",
    "Compact": "Paragraphedeliste",
    # Code (pandoc source code styles → OBA code style)
    "SourceCode": "Code",
    "VerbatimChar": "CodeCar",
    # Pandoc syntax highlighting token styles (character styles)
    # These don't have OBA equivalents — keep them as-is or map to code
    "NormalTok": "CodeCar",
    "KeywordTok": "CodeCar",
    "DataTypeTok": "CodeCar",
    "DecValTok": "CodeCar",
    "FunctionTok": "CodeCar",
    "CharTok": "CodeCar",
    "StringTok": "CodeCar",
    "CommentTok": "CodeCar",
    "OperatorTok": "CodeCar",
    "BuiltInTok": "CodeCar",
    "ExtensionTok": "CodeCar",
    "AttributeTok": "CodeCar",
    "VariableTok": "CodeCar",
}


def _w(tag):
    return f"{{{W_NS}}}{tag}"


def _build_version_table(date, author):
    """Build a proper 4-column version table for the cover page.

    Columns: Date | Objet | Auteur | Version
    Row 1 (header): blue background, white bold text
    Row 2 (data): date, "Création", author, "1.0"
    """
    HEADER_FILL = "233F70"  # OBA navy
    HEADER_TEXT_COLOR = "FFFFFF"
    BORDER_COLOR = "CCCCCC"
    TABLE_WIDTH = 9350  # Full width A4 with margins (DXA)
    COL_WIDTHS = [1800, 3750, 2200, 1600]  # Date, Objet, Auteur, Version

    tbl = etree.Element(_w("tbl"))

    # Table properties (OOXML order: tblW → tblBorders → tblLook)
    tblPr = etree.SubElement(tbl, _w("tblPr"))
    tblW = etree.SubElement(tblPr, _w("tblW"))
    tblW.set(_w("w"), str(TABLE_WIDTH))
    tblW.set(_w("type"), "dxa")
    # Borders (must come before tblLook in OOXML schema)
    tblBorders = etree.SubElement(tblPr, _w("tblBorders"))
    for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
        b = etree.SubElement(tblBorders, _w(side))
        b.set(_w("val"), "single")
        b.set(_w("sz"), "4")
        b.set(_w("space"), "0")
        b.set(_w("color"), BORDER_COLOR)
    tblLook = etree.SubElement(tblPr, _w("tblLook"))
    tblLook.set(_w("val"), "04A0")
    tblLook.set(_w("firstRow"), "1")

    # Grid
    tblGrid = etree.SubElement(tbl, _w("tblGrid"))
    for w in COL_WIDTHS:
        gridCol = etree.SubElement(tblGrid, _w("gridCol"))
        gridCol.set(_w("w"), str(w))

    def _make_cell(text, width, bold=False, shading=None, text_color=None):
        tc = etree.Element(_w("tc"))
        tcPr = etree.SubElement(tc, _w("tcPr"))
        tcW = etree.SubElement(tcPr, _w("tcW"))
        tcW.set(_w("w"), str(width))
        tcW.set(_w("type"), "dxa")
        if shading:
            shd = etree.SubElement(tcPr, _w("shd"))
            shd.set(_w("val"), "clear")
            shd.set(_w("color"), "auto")
            shd.set(_w("fill"), shading)
        p = etree.SubElement(tc, _w("p"))
        r = etree.SubElement(p, _w("r"))
        rPr = etree.SubElement(r, _w("rPr"))
        rFonts = etree.SubElement(rPr, _w("rFonts"))
        rFonts.set(_w("ascii"), "Arial")
        rFonts.set(_w("hAnsi"), "Arial")
        sz = etree.SubElement(rPr, _w("sz"))
        sz.set(_w("val"), "18")  # 9pt
        szCs = etree.SubElement(rPr, _w("szCs"))
        szCs.set(_w("val"), "18")
        if bold:
            etree.SubElement(rPr, _w("b"))
            etree.SubElement(rPr, _w("bCs"))
        if text_color:
            color = etree.SubElement(rPr, _w("color"))
            color.set(_w("val"), text_color)
        t = etree.SubElement(r, _w("t"))
        t.text = text
        t.set("{http://www.w3.org/XML/1998/namespace}space", "preserve")
        return tc

    # Header row
    headers = ["Date", "Objet", "Auteur", "Version"]
    header_tr = etree.SubElement(tbl, _w("tr"))
    for hi, h in enumerate(headers):
        header_tr.append(_make_cell(h, COL_WIDTHS[hi], bold=True, shading=HEADER_FILL, text_color=HEADER_TEXT_COLOR))

    # Data row
    data_tr = etree.SubElement(tbl, _w("tr"))
    data_row = [date or "", "Création", author or "", "1.0"]
    for di, d in enumerate(data_row):
        data_tr.append(_make_cell(d, COL_WIDTHS[di]))

    return tbl


def extract_cover_elements(template_path):
    """Extract cover page elements (2 tables + spacing) from template-base.docx.

    Returns (elements_list, media_files_dict, image_rels_list)
    """
    with zipfile.ZipFile(template_path) as z:
        doc_xml = z.read("word/document.xml")
        rels_xml = z.read("word/_rels/document.xml.rels")

        media_files = {}
        for name in z.namelist():
            if name.startswith("word/media/"):
                media_files[name] = z.read(name)

        rels_tree = etree.fromstring(rels_xml)
        image_rels = []
        for rel in rels_tree:
            if rel.get("Type", "") == REL_IMAGE_TYPE:
                image_rels.append({
                    "id": rel.get("Id"),
                    "target": rel.get("Target"),
                })

    tree = etree.fromstring(doc_xml)
    body = tree.find(_w("body"))
    children = list(body)

    # Cover = elements [0] to [7]:
    # [0] = title/logo table, [1-5] = spacing, [6] = version table, [7] = trailing para
    cover_elements = []
    for i in range(min(8, len(children))):
        child = children[i]
        tag = child.tag.split("}")[-1] if "}" in child.tag else child.tag
        if tag == "p":
            pStyle = child.find(f".//{{{W_NS}}}pStyle")
            if pStyle is not None and "Titre" in pStyle.get(f"{{{W_NS}}}val", ""):
                break
        cover_elements.append(child)

    return cover_elements, media_files, image_rels


def inject_cover(input_docx, output_docx, title, subtitle="", author="", date=""):
    """Inject cover page into a pandoc-generated DOCX."""

    tmpdir = tempfile.mkdtemp()

    try:
        # === Step 1: Extract input DOCX ===
        input_dir = os.path.join(tmpdir, "input")
        with zipfile.ZipFile(input_docx, "r") as z:
            z.extractall(input_dir)

        # === Step 2: Transplant template files (styles, numbering, etc.) ===
        with zipfile.ZipFile(TEMPLATE_BASE) as zt:
            files_to_transplant = [
                "word/styles.xml",
                "word/numbering.xml",
                "word/settings.xml",
                "word/theme/theme1.xml",
                "word/endnotes.xml",
            ]
            if "word/footer1.xml" in zt.namelist():
                files_to_transplant.append("word/footer1.xml")

            for fname in files_to_transplant:
                if fname in zt.namelist():
                    dest = os.path.join(input_dir, fname)
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    with open(dest, "wb") as f:
                        f.write(zt.read(fname))
        print(f"Transplanted {len(files_to_transplant)} template files (styles, numbering, settings, theme, footer)")

        # === Step 3: Extract cover elements and media from template ===
        cover_elements, media_files, template_image_rels = extract_cover_elements(TEMPLATE_BASE)

        media_dir = os.path.join(input_dir, "word", "media")
        os.makedirs(media_dir, exist_ok=True)
        for media_path, media_data in media_files.items():
            dest = os.path.join(input_dir, media_path)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "wb") as f:
                f.write(media_data)

        # === Step 4: Update relationships (single parse) ===
        rels_path = os.path.join(input_dir, "word", "_rels", "document.xml.rels")
        rels_tree = etree.parse(rels_path)
        rels_root = rels_tree.getroot()

        existing_rids = set(rel.get("Id", "") for rel in rels_root)
        footer_rid_for_sectpr = None

        # Add image relationships
        for img_rel in template_image_rels:
            if img_rel["id"] not in existing_rids:
                new_rel = etree.SubElement(rels_root, "Relationship")
                new_rel.set("Id", img_rel["id"])
                new_rel.set("Type", REL_IMAGE_TYPE)
                new_rel.set("Target", img_rel["target"])
                existing_rids.add(img_rel["id"])

        # Add endnotes relationship if missing
        REL_ENDNOTES_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes"
        has_endnotes_rel = any(
            rel.get("Type", "") == REL_ENDNOTES_TYPE for rel in rels_root
        )
        if not has_endnotes_rel:
            max_id = max(
                (int(rid[3:]) for rid in existing_rids if rid.startswith("rId") and rid[3:].isdigit()),
                default=0,
            )
            endnotes_rid = f"rId{max_id + 1}"
            new_rel = etree.SubElement(rels_root, "Relationship")
            new_rel.set("Id", endnotes_rid)
            new_rel.set("Type", REL_ENDNOTES_TYPE)
            new_rel.set("Target", "endnotes.xml")
            existing_rids.add(endnotes_rid)

        # Add footer relationship
        has_footer_rel = any(
            rel.get("Type", "") == REL_FOOTER_TYPE for rel in rels_root
        )
        if not has_footer_rel:
            max_id = max(
                (int(rid[3:]) for rid in existing_rids if rid.startswith("rId") and rid[3:].isdigit()),
                default=0,
            )
            footer_rid = f"rId{max_id + 1}"
            new_rel = etree.SubElement(rels_root, "Relationship")
            new_rel.set("Id", footer_rid)
            new_rel.set("Type", REL_FOOTER_TYPE)
            new_rel.set("Target", "footer1.xml")
            footer_rid_for_sectpr = footer_rid

        rels_tree.write(rels_path, xml_declaration=True, encoding="UTF-8", standalone=True)

        # === Step 5: Update [Content_Types].xml (single parse) ===
        ct_path = os.path.join(input_dir, "[Content_Types].xml")
        ct_tree = etree.parse(ct_path)
        ct_root = ct_tree.getroot()

        # Add image extensions
        existing_extensions = set(
            d.get("Extension", "") for d in ct_root.findall(f"{{{CT_NS}}}Default")
        )
        image_types = {"png": "image/png", "svg": "image/svg+xml", "jpeg": "image/jpeg", "jpg": "image/jpeg"}
        for ext, ctype in image_types.items():
            if ext not in existing_extensions and any(f.endswith(f".{ext}") for f in media_files):
                default = etree.SubElement(ct_root, f"{{{CT_NS}}}Default")
                default.set("Extension", ext)
                default.set("ContentType", ctype)

        # Add endnotes + footer content types
        existing_overrides = set(
            o.get("PartName", "") for o in ct_root.findall(f"{{{CT_NS}}}Override")
        )
        if "/word/endnotes.xml" not in existing_overrides:
            override = etree.SubElement(ct_root, f"{{{CT_NS}}}Override")
            override.set("PartName", "/word/endnotes.xml")
            override.set("ContentType", "application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml")
        if "/word/footer1.xml" not in existing_overrides:
            override = etree.SubElement(ct_root, f"{{{CT_NS}}}Override")
            override.set("PartName", "/word/footer1.xml")
            override.set("ContentType", "application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml")

        ct_tree.write(ct_path, xml_declaration=True, encoding="UTF-8", standalone=True)

        # === Step 6: Modify document.xml ===
        doc_path = os.path.join(input_dir, "word", "document.xml")
        doc_tree = etree.parse(doc_path)
        doc_root = doc_tree.getroot()
        body = doc_root.find(_w("body"))

        # 6a. Remap pandoc style IDs to OBA template style IDs
        # For paragraph styles: context-aware mapping
        remap_count = 0
        for para in body.iter(_w("p")):
            pPr = para.find(_w("pPr"))
            if pPr is None:
                continue
            pStyle = pPr.find(_w("pStyle"))
            if pStyle is None:
                continue
            val = pStyle.get(_w("val"), "")
            if val == "Compact":
                # Compact + numPr = list item → Paragraphedeliste
                # Compact without numPr = table cell → Normal
                has_numPr = pPr.find(_w("numPr")) is not None
                pStyle.set(_w("val"), "Paragraphedeliste" if has_numPr else "Normal")
                remap_count += 1
            elif val in PANDOC_STYLE_MAP:
                pStyle.set(_w("val"), PANDOC_STYLE_MAP[val])
                remap_count += 1

        # For run styles: only remap code token styles (NormalTok, KeywordTok, etc.)
        # when they are INSIDE a paragraph with Code/SourceCode style.
        # Outside code blocks, these token styles should be REMOVED (not remapped)
        # to avoid applying CodeCar formatting to headings, tables, etc.
        CODE_TOKEN_STYLES = {
            "NormalTok", "KeywordTok", "DataTypeTok", "DecValTok",
            "FunctionTok", "CharTok", "StringTok", "CommentTok",
            "OperatorTok", "BuiltInTok", "ExtensionTok", "AttributeTok",
            "VariableTok", "VerbatimChar",
        }
        for para in body.iter(_w("p")):
            # Determine if this paragraph is a code block
            para_pStyle = para.find(f"./{_w('pPr')}/{_w('pStyle')}")
            para_style = para_pStyle.get(_w("val"), "") if para_pStyle is not None else ""
            is_code_para = para_style in ("Code", "SourceCode", "PrformatHTML")

            for rStyle in para.iter(_w("rStyle")):
                val = rStyle.get(_w("val"), "")
                if val in CODE_TOKEN_STYLES:
                    if is_code_para:
                        # Inside code block: remap to CodeCar
                        rStyle.set(_w("val"), "CodeCar")
                        remap_count += 1
                    else:
                        # Outside code block: remove the rStyle entirely
                        # (don't apply code formatting to headings/tables/normal text)
                        rPr = rStyle.getparent()
                        if rPr is not None:
                            rPr.remove(rStyle)
                        remap_count += 1
                elif val in PANDOC_STYLE_MAP:
                    rStyle.set(_w("val"), PANDOC_STYLE_MAP[val])
                    remap_count += 1

        if remap_count:
            print(f"Remapped {remap_count} style reference(s) from pandoc IDs to OBA IDs")

        # 6b. Remove horizontal rule separators (empty paragraphs between headings)
        # Pandoc renders markdown --- as empty paragraphs; also remove pBdr-based HRs
        hr_removed = 0
        children_list = list(body)
        for i, child in enumerate(children_list):
            if child.tag != _w("p"):
                continue
            # Check if this is an empty paragraph (no text) between two headings
            texts = [t.text for t in child.iter(_w("t")) if t.text and t.text.strip()]
            if texts:
                continue
            pPr = child.find(_w("pPr"))
            # Remove paragraphs with borders (explicit HR)
            if pPr is not None and pPr.find(_w("pBdr")) is not None:
                body.remove(child)
                hr_removed += 1
                continue
            # Remove empty paragraphs with no style that sit between headings
            pStyle = pPr.find(_w("pStyle")) if pPr is not None else None
            if pStyle is not None:
                continue  # Has a style — not an HR separator
            # Check neighbors: if previous or next sibling is a heading, this is likely an HR
            if i > 0 and i < len(children_list) - 1:
                prev_style = children_list[i - 1].find(f".//{_w('pStyle')}")
                next_el = children_list[i + 1] if i + 1 < len(children_list) else None
                next_style = next_el.find(f".//{_w('pStyle')}") if next_el is not None else None
                prev_is_heading = prev_style is not None and "Titre" in prev_style.get(_w("val"), "")
                next_is_heading = next_style is not None and "Titre" in next_style.get(_w("val"), "")
                # Also check bookmarkStart/End (pandoc inserts these before headings)
                next_is_bookmark = next_el is not None and "bookmark" in (next_el.tag.split("}")[-1] if "}" in next_el.tag else next_el.tag)
                if prev_is_heading or next_is_heading or next_is_bookmark:
                    body.remove(child)
                    hr_removed += 1
        if hr_removed:
            print(f"Removed {hr_removed} horizontal rule separator(s)")

        # 6c. Add light gray borders to content tables (not cover page tables)
        TABLE_BORDER_COLOR = "CCCCCC"
        tables_fixed = 0
        for tbl in body.findall(_w("tbl")):
            # Skip tables that are part of the cover page (they have tblBorders=none intentionally)
            first_cell_texts = [t.text for t in tbl.iter(_w("t")) if t.text][:3]
            # Cover tables contain title/version — skip them
            if any(k in " ".join(first_cell_texts) for k in [title, "VERSION", subtitle]):
                continue
            # Add or replace tblBorders with light gray
            tblPr = tbl.find(_w("tblPr"))
            if tblPr is None:
                tblPr = etree.SubElement(tbl, _w("tblPr"))
                tbl.insert(0, tblPr)
            # Remove existing tblBorders
            existing_borders = tblPr.find(_w("tblBorders"))
            if existing_borders is not None:
                tblPr.remove(existing_borders)
            # Build new borders element
            tblBorders = etree.Element(_w("tblBorders"))
            for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
                border = etree.SubElement(tblBorders, _w(side))
                border.set(_w("val"), "single")
                border.set(_w("sz"), "4")
                border.set(_w("space"), "0")
                border.set(_w("color"), TABLE_BORDER_COLOR)
            # Insert tblBorders in correct OOXML order (after tblW/jc/tblInd, before tblLook/tblCaption)
            insert_pos = len(list(tblPr))  # default: end
            for pi, pchild in enumerate(list(tblPr)):
                ptag = pchild.tag.split("}")[-1] if "}" in pchild.tag else pchild.tag
                if ptag in ("tblLook", "tblCaption", "tblDescription", "shd", "tblLayout", "tblCellMar"):
                    insert_pos = pi
                    break
            tblPr.insert(insert_pos, tblBorders)
            tables_fixed += 1
        if tables_fixed:
            print(f"Added gray borders to {tables_fixed} content table(s)")

        # 6c-bis. Remove left indent inside table cells (pandoc adds w:ind to cell paragraphs)
        indent_removed = 0
        for tbl in body.findall(_w("tbl")):
            for tc in tbl.iter(_w("tc")):
                for p in tc.findall(_w("p")):
                    pPr = p.find(_w("pPr"))
                    if pPr is not None:
                        ind = pPr.find(_w("ind"))
                        if ind is not None:
                            pPr.remove(ind)
                            indent_removed += 1
        if indent_removed:
            print(f"Removed {indent_removed} left indent(s) from table cells")

        # 6d. Replace placeholders in cover elements and rebuild version table
        for elem in cover_elements:
            for t_elem in elem.iter(_w("t")):
                if t_elem.text is None:
                    continue
                t_elem.text = (
                    t_elem.text
                    .replace("[TITRE DU DOCUMENT]", title)
                    .replace("[Sous-titre du document]", subtitle)
                    .replace("[Auteur]", author)
                    .replace("[Date]", date)
                )

        # Rebuild version table (replace the simple 1-col table with a proper 4-col one)
        # Find the version table in cover_elements (the one containing "VERSION")
        for i, elem in enumerate(cover_elements):
            if elem.tag == _w("tbl"):
                texts = [t.text for t in elem.iter(_w("t")) if t.text]
                if "VERSION" in " ".join(texts):
                    new_tbl = _build_version_table(date, author)
                    cover_elements[i] = new_tbl
                    break

        # 6e. Remove redundant Title/Subtitle paragraphs from pandoc body
        # (pandoc maps # H1 with --shift-heading-level-by=-1 to Title style)
        to_remove = []
        for child in list(body):
            if child.tag != _w("p"):
                continue
            pStyle = child.find(f".//{_w('pStyle')}")
            if pStyle is None:
                continue
            style_val = pStyle.get(_w("val"), "")
            if style_val in ("Title", "Titre", "Subtitle", "Sous-titre"):
                to_remove.append(child)
            elif "eading" in style_val or style_val.startswith("Titre"):
                break  # Stop at first real heading

        for elem in to_remove:
            body.remove(elem)
        if to_remove:
            print(f"Removed {len(to_remove)} redundant Title/Subtitle paragraph(s) from body")

        # 6f. Insert cover + page break at the start
        page_break = etree.Element(_w("p"))
        r = etree.SubElement(page_break, _w("r"))
        br = etree.SubElement(r, _w("br"))
        br.set(_w("type"), "page")

        insert_idx = 0
        for elem in cover_elements:
            body.insert(insert_idx, elem)
            insert_idx += 1
        body.insert(insert_idx, page_break)

        # 6g. Add footerReference to sectPr if needed
        # OOXML requires footerReference early in sectPr (before endnotePr, pgSz, etc.)
        if footer_rid_for_sectpr:
            for sectPr in doc_root.findall(f".//{_w('sectPr')}"):
                footer_ref = etree.Element(_w("footerReference"))
                footer_ref.set(_w("type"), "default")
                footer_ref.set(f"{{{R_NS}}}id", footer_rid_for_sectpr)
                sectPr.insert(0, footer_ref)

        doc_tree.write(doc_path, xml_declaration=True, encoding="UTF-8", standalone=True)

        # === Step 7: Pack and validate ===
        pack_script = str(OFFICE_DIR / "pack.py")
        result = subprocess.run(
            ["python3", pack_script, input_dir, output_docx, "--original", input_docx],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"Pack error:\n{result.stdout}\n{result.stderr}", file=sys.stderr)
            sys.exit(1)
        print(result.stdout, end="")

        validate_script = str(OFFICE_DIR / "validate.py")
        result = subprocess.run(
            ["python3", validate_script, output_docx],
            capture_output=True, text=True,
        )
        print(result.stdout, end="")
        if result.returncode != 0:
            print(f"Validation warnings: {result.stderr}", file=sys.stderr)

        print(f"Success: {output_docx}")

    finally:
        shutil.rmtree(tmpdir)


def main():
    parser = argparse.ArgumentParser(description="Inject OBA cover page into pandoc DOCX output")
    parser.add_argument("input", help="Input DOCX (pandoc-generated)")
    parser.add_argument("output", help="Output DOCX with cover page")
    parser.add_argument("--title", required=True, help="Document title")
    parser.add_argument("--subtitle", default="", help="Document subtitle")
    parser.add_argument("--author", default="", help="Author name")
    parser.add_argument("--date", default="", help="Date (DD/MM/YYYY)")

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: {args.input} not found", file=sys.stderr)
        sys.exit(1)

    inject_cover(args.input, args.output, args.title, args.subtitle, args.author, args.date)


if __name__ == "__main__":
    main()
